### ISSUE TITLE
Make it work with @JsonAdapter

### ISSUE THREAD

**Issue by thuytrinh** [rharter/auto-value-gson#11]
Given model class:
```java
@AutoValue
@JsonAdapter(AutoValue_Item.ItemTypeAdapter.class)
public abstract class Item {
  public static Builder builder() {
    return new AutoValue_Item.Builder();
  }

  public abstract long id();
  public abstract String name();

  @AutoValue.Builder
  public static abstract class Builder {
    public abstract Builder id(long id);
    public abstract Builder name(String name);
    public abstract Item build();
  }
}
```

Following test will fail:
```java
public class ItemTest {
  @Test public void gson() {
    final Item i0 = Item.builder().id(1).name("Awesome!").build();
    final Gson gson = new Gson();
    final String json = gson.toJson(i0);
    final Item i1 = gson.fromJson(json, Item.class); // Will fail!
    assertThat(i1).isEqualTo(i0);
  }
}
```

With stack trace:
```
java.lang.NullPointerException
	at com.thuytrinh.android.autosamples.AutoValue_Item$ItemTypeAdapter.read(AutoValue_Item.java:61)
	at com.thuytrinh.android.autosamples.AutoValue_Item$ItemTypeAdapter.read(AutoValue_Item.java:32)
	at com.google.gson.Gson.fromJson(Gson.java:861)
	at com.google.gson.Gson.fromJson(Gson.java:826)
	at com.google.gson.Gson.fromJson(Gson.java:775)
	at com.google.gson.Gson.fromJson(Gson.java:747)
```

**Comment by thuytrinh** [comment]
Oh my mistake! Turns out `JsonAdapter` can work with `TypeAdapterFactory` too. So I should have declared `@JsonAdapter(AutoValue_Item.ItemTypeAdapterFactory.class)` instead of `@JsonAdapter(AutoValue_Item.ItemTypeAdapter.class)`. This way `gson` will be able to pick correctly the generated factory class which invokes the constructor having gson param.

I'll close this issue but is this @JsonAdapter usage the **Automatic registration** you mentioned in https://github.com/rharter/auto-value-gson#todo @rharter?

**Comment by rharter** [comment]
It looks like that is the automatic registration we've been looking for. Thanks, @thuytrinh!
