### ISSUE TITLE
Unable to create model with HashMap

### ISSUE THREAD

**Issue by Aditya-Sh** [rharter/auto-value-gson#127]
I am trying to create model class where I need a HashMap with a String and List\<String> value.
Below is my definition in class
`@SerializedName("shows")
  public abstract HashMap<String, List<String>> shows();`

I am getting
`error: <identifier> expected` on List\<String>

**Comment by hzsweers** [comment]
Please give a full stacktrace and reproducible sample

**Comment by Aditya-Sh** [comment]
It fails on compilation itself. The error is the same I mentioned above.
Sample code for my class:
`public abstract class Movie implements Parcelable {

    @SerializedName("shows")
    public abstract HashMap<String, List<String>> shows();

    public static Builder builder() {
        return new AutoValue_Movie.Builder();
    }

    public static TypeAdapter<Movie> typeAdapter(Gson gson) {
        return new AutoValue_Movie.GsonTypeAdapter(gson);
    }

    public static Movie create(Movie movie) {
        return movie.shows());
    }

    @AutoValue.Builder
    public abstract static class Builder{
        public abstract Builder setShows(HashMap<String, List<String>> shows);
        public abstract Movie build();

    }
}`

**Comment by hzsweers** [comment]
Please give the full stacktrace

**Comment by Aditya-Sh** [comment]
Sorry, missed it last time.
Here it is:
`Information:Gradle tasks [:app:assembleDebug]
/mobile-apps-android/app/build/generated/source/apt/debug/za/co/venueengage/app/data/model/AutoValue_Movie.java
Error:(31, 62) error: <identifier> expected
Error:Execution failed for task ':app:compileDebugJavaWithJavac'.
\> Compilation failed; see the compiler error output for details.
Information:BUILD FAILED
Information:Total time: 21.218 secs
Information:2 errors
Information:0 warnings
Information:See complete output in console`

**Comment by hzsweers** [comment]
That's still not the actual stacktrace. Run with --stacktrace. Better yet, fork the project and demo this issue in the sample or a test

**Comment by Aditya-Sh** [comment]
This is the error in gradle console:
`/mobile-apps-android/app/build/generated/source/apt/debug/za/co/venueengage/app/data/model/AutoValue_Movie.java:31: error: \<identifier\> expected
          (HashMap\<String, List\<String\>\>) in.readHashMap(List\<E>.class.getClassLoader())
                                                                 ^
1 error

 FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
\> Compilation failed; see the compiler error output for details.

* Try:
Run with --info or --debug option to get more log output.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':app:compileDebugJavaWithJavac'.
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:69)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:46)
	at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExecuter.execute(PostExecutionAnalysisTaskExecuter.java:35)
	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:66)
	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:52)
	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:53)
	at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:203)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:185)
	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:66)
	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:50)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
	at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
Caused by: org.gradle.api.internal.tasks.compile.CompilationFailedException: Compilation failed; see the compiler error output for details.
	at org.gradle.api.internal.tasks.compile.JdkJavaCompiler.execute(JdkJavaCompiler.java:48)
	at org.gradle.api.internal.tasks.compile.JdkJavaCompiler.execute(JdkJavaCompiler.java:33)
	at org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler.delegateAndHandleErrors(NormalizingJavaCompiler.java:104)
	at org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler.execute(NormalizingJavaCompiler.java:53)
	at org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler.execute(NormalizingJavaCompiler.java:38)
	at org.gradle.api.internal.tasks.compile.CleaningJavaCompilerSupport.execute(CleaningJavaCompilerSupport.java:35)
	at org.gradle.api.internal.tasks.compile.CleaningJavaCompilerSupport.execute(CleaningJavaCompilerSupport.java:25)
	at org.gradle.api.tasks.compile.JavaCompile.performCompilation(JavaCompile.java:163)
	at org.gradle.api.tasks.compile.JavaCompile.compile(JavaCompile.java:145)
	at org.gradle.api.tasks.compile.JavaCompile.compile(JavaCompile.java:93)
	at com.android.build.gradle.tasks.factory.AndroidJavaCompile.compile(AndroidJavaCompile.java:49)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:75)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$IncrementalTaskAction.doExecute(AnnotationProcessingTaskFactory.java:245)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:221)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$IncrementalTaskAction.execute(AnnotationProcessingTaskFactory.java:232)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:210)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
	... 14 more


BUILD FAILED

Total time: 24.799 secs`

**Comment by JakeWharton** [comment]
Seems like a problem with the parcel extension, not this one. And I already
have a PR out to fix it.
