### ISSUE TITLE
Do you have any  plan to develop a "auto-value-android-data-binding" tool?

### ISSUE THREAD

**Issue by Guang1234567** [rharter/auto-value-gson#129]
Hello rharter:
   I am your auto-value-XXX's  fans, it save a lot of time, thanks a lot.

  Do you have any plan or interest to develop a "auto-value-android-data-binding" tool?
  

>What is  android-data-binding?
https://developer.android.com/topic/libraries/data-binding/index.html
https://news.realm.io/cn/news/data-binding-android-boyar-mount/

**Comment by JakeWharton** [comment]
Which does what?

**Comment by rharter** [comment]
Hey @LiHanGuang.  What do you suggest an `auto-value-android-data-binding` would of? Immutability would prevent the use of Observable (which is fine if you choose), and without that you can already use AutoValue objects with Data Binding.

**Comment by JakeWoki** [comment]
[use dataBinding error](https://github.com/rharter/auto-value-gson/issues/159)

**Comment by hzsweers** [comment]
@JakeWoki please take a look at @rharter's previous comment. Closing #159 in favor of consolidating discussion here. In short, unless you're willing to forgo the use of Observable in data binding (which seems to fly in the face of its purpose), I think autovalue isn't the right tool for data binding.

**Comment by JakeWoki** [comment]
* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> android.databinding.tool.util.LoggedErrorException: Found data binding errors.
  ****/ data binding error ****msg:The expression userInfo.userName() cannot be inverted: Two-way binding cannot resolve a setter for java.lang.String property 'userName'
  loc:48:37 - 48:53
  ****\ data binding error ****

``` Java
@AutoValue
public abstract class UserInfo {

	public abstract String avatar();

	@SerializedName("username")
	public abstract String userName();

	@SerializedName("realname")
	public abstract String realName();

	public static TypeAdapter<UserInfo> typeAdapter(Gson gson) {
		return new AutoValue_UserInfo.GsonTypeAdapter(gson);
	}
}

<?xml version="1.0" encoding="utf-8"?>
<layout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools">

    <data>
        <import type="com..model.UserInfo"/>
        <variable name="userInfo" type="UserInfo"/>
    </data>

    <ScrollView
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:background="@android:color/white">
        <LinearLayout
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            android:orientation="vertical">

            <TextView
                    android:id="@+id/name"
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:textColor="@color/titleColor"
                    android:textSize="24sp"
                    android:text="@={userInfo.userName}"/>

        </LinearLayout>
    </ScrollView>

</layout>
```
can you give som help?

**Comment by hzsweers** [comment]
@JakeWoki is that a request? error? That needs more information to really be actionable.

I'm kind of also of the inclination that this repo isn't the best place to discuss databinding issues. This repo is for autovalue + gson, not autovalue + databinding.

**Comment by JakeWoki** [comment]
``` Java
View field userInfo collides with a variable or import
  file://D:\soft\android\app\src\main\res\layout\fragment_me.xml Line:19

:app:compileDebugJavaWithJavac FAILED
:app:compileDebugJavaWithJavac (Thread[Task worker for ':',5,main]) completed. Took 1.65 secs.
:app:buildInfoGeneratorDebug (Thread[Task worker for ':',5,main]) started.
:app:buildInfoGeneratorDebug
Putting task artifact state for task ':app:buildInfoGeneratorDebug' into context took 0.0 secs.
Executing task ':app:buildInfoGeneratorDebug' (up-to-date check took 0.0 secs) due to:
  Task has not declared any outputs.
:app:buildInfoGeneratorDebug (Thread[Task worker for ':',5,main]) completed. Took 0.005 secs.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> android.databinding.tool.util.LoggedErrorException: Found data binding errors.
  ****/ data binding error ****msg:The expression userInfo.userName() cannot be inverted: Two-way binding cannot resolve a setter for java.lang.String property 'userName'
  file:D:\soft\android\app\src\main\res\layout\fragment_me.xml
  loc:48:37 - 48:53
  ****\ data binding error ****


* Try:
Run with --debug option to get more log output.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':app:compileDebugJavaWithJavac'.
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:100)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:70)
	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:63)
	at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:88)
	at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:52)
	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
	at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.run(DefaultTaskGraphExecuter.java:248)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:197)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:107)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:241)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:230)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.processTask(DefaultTaskPlanExecutor.java:124)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.access$200(DefaultTaskPlanExecutor.java:80)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:105)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:99)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.execute(DefaultTaskExecutionPlan.java:625)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.executeWithTask(DefaultTaskExecutionPlan.java:580)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.run(DefaultTaskPlanExecutor.java:99)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.RuntimeException: android.databinding.tool.util.LoggedErrorException: Found data binding errors.
****/ data binding error ****msg:The expression userInfo.userName() cannot be inverted: Two-way binding cannot resolve a setter for java.lang.String property 'userName'
file:D:\soft\android\app\src\main\res\layout\fragment_me.xml
loc:48:37 - 48:53
****\ data binding error ****

	at com.sun.tools.javac.main.Main.compile(Main.java:553)
	at com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:129)
	at com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:138)
	at org.gradle.api.internal.tasks.compile.JdkJavaCompiler.execute(JdkJavaCompiler.java:49)
	at org.gradle.api.internal.tasks.compile.JdkJavaCompiler.execute(JdkJavaCompiler.java:36)
	at org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler.delegateAndHandleErrors(NormalizingJavaCompiler.java:99)
	at org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler.execute(NormalizingJavaCompiler.java:52)
	at org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler.execute(NormalizingJavaCompiler.java:37)
	at org.gradle.api.internal.tasks.compile.CleaningJavaCompilerSupport.execute(CleaningJavaCompilerSupport.java:35)
	at org.gradle.api.internal.tasks.compile.CleaningJavaCompilerSupport.execute(CleaningJavaCompilerSupport.java:25)
	at org.gradle.api.tasks.compile.JavaCompile.performCompilation(JavaCompile.java:198)
	at org.gradle.api.tasks.compile.JavaCompile.compile(JavaCompile.java:183)
	at org.gradle.api.tasks.compile.JavaCompile.compile(JavaCompile.java:120)
	at com.android.build.gradle.tasks.factory.AndroidJavaCompile.compile(AndroidJavaCompile.java:95)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
	at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$IncrementalTaskAction.doExecute(DefaultTaskClassInfoStore.java:173)
	at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:134)
	at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:121)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:122)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:197)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:107)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:111)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:92)
	... 30 more
Caused by: android.databinding.tool.util.LoggedErrorException: Found data binding errors.
****/ data binding error ****msg:The expression userInfo.userName() cannot be inverted: Two-way binding cannot resolve a setter for java.lang.String property 'userName'
file:D:\soft\android\app\src\main\res\layout\fragment_me.xml
loc:48:37 - 48:53
****\ data binding error ****

	at android.databinding.tool.processing.Scope.assertNoError(Scope.java:112)
	at android.databinding.annotationprocessor.ProcessDataBinding.process(ProcessDataBinding.java:91)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:794)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.access$200(JavacProcessingEnvironment.java:91)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment$DiscoveredProcessors$ProcessorStateIterator.runContributingProcs(JavacProcessingEnvironment.java:627)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1033)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1198)
	at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1170)
	at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:856)
	at com.sun.tools.javac.main.Main.compile(Main.java:523)
	... 58 more


* Get more help at https://help.gradle.org

BUILD FAILED in 4s
```

**Comment by hzsweers** [comment]
@JakeWoki you're just pasting stacktraces, it would help if you explained what you were trying to do or expecting.

**Comment by JakeWoki** [comment]
I hope autovalue + gson + databinding

**Comment by hzsweers** [comment]
I'm afraid you can't, which is kind of the point of this thread. DataBinding does not support abstract classes because it doesn't know how to instantiate them. You could try to do something where you expose the generated autovalue class to databinding, but you could only ever do field binding. I don't think this is possible though, as the documentation only seems to allow for custom setter routing (which obviously is incompatible with autovalue since it's immutable).

I'm going to close this issue, as I don't think there's anything further that can be done. I would recommend decoupling your viewmodels from your data models.

**Comment by rharter** [comment]
@JakeWoki The first error you listed shows an error with two way data binding, which requires both a setter and a getter.  AutoValue creates *immutable* data classes, so they don't have setters, which is why this won't work.

I'm not a databinding expert, so I'm not sure if you can turn off two way data binding, but StackOverflow is the appropriate forum for that type of question.
