### ISSUE TITLE
IllegalArgumentException: cannot unindent 1 from 0

### ISSUE THREAD

**Issue by ben-manes** [rharter/auto-value-gson#170]
When generating the adapter factory with a stub, it fails with a JavaPoet indention error.

```java
@GsonTypeAdapterFactory
public abstract class AutoValueTypeAdapterFactory implements TypeAdapterFactory {
  public static AutoValueTypeAdapterFactory create() {
    return null;
  }
}
```

```
Caused by: java.lang.IllegalArgumentException: cannot unindent 1 from 0
        at com.squareup.javapoet.Util.checkArgument(Util.java:64)
        at com.squareup.javapoet.CodeWriter.unindent(CodeWriter.java:107)
        at com.squareup.javapoet.CodeWriter.unindent(CodeWriter.java:103)
        at com.squareup.javapoet.TypeSpec.emit(TypeSpec.java:320)
        at com.squareup.javapoet.JavaFile.emit(JavaFile.java:157)
        at com.squareup.javapoet.JavaFile.writeTo(JavaFile.java:77)
        at com.squareup.javapoet.JavaFile.writeTo(JavaFile.java:117)
        at com.ryanharter.auto.value.gson.AutoValueGsonAdapterFactoryProcessor.process(AutoValueGsonAdapterFactoryProcessor.java:101)
        at com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:794)
        at com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:705)
        at com.sun.tools.javac.processing.JavacProcessingEnvironment.access$1800(JavacProcessingEnvironment.java:91)
        at com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1035)
        at com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1176)
        at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1170)
        at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:856)
        at com.sun.tools.javac.main.Main.compile(Main.java:523)
        ... 59 more
```

**Comment by hzsweers** [comment]
Haven't seen your code but I suspect it's because it didn't find any autovalue models on the compilation classpath

**Comment by hzsweers** [comment]
Assuming that's it, yeah the error message could be better :)

**Comment by ben-manes** [comment]
The autoValue plugin uses its own sourceSet configuration, not Java's srcDir, which might be the issue. That can compile fine in Gradle but sometimes confuses Eclipse. Might be a hard coded assumption in `AutoValueGsonAdapterFactoryProcessor`.

Unfortunately I see other weird interactions, e.g. when having multiple gson autoValue models in an interface, that fail non-descriptively. Seems like similar conflicting assumptions between tooling.

**Comment by jffiorillo** [comment]
I'm having same issue here with `0.7.0` version!
