### ISSUE TITLE
Failed to invoke public com.ramiissa.dubaiing.data.network.model.news.NewsResponse() with no args

### ISSUE THREAD

**Issue by alihabbash** [rharter/auto-value-gson#184]
Hi, I have an AutoValue class for newsResponse and `RxJava` with `Retrofit`
and my AutoValue type adapter is

    @AutoValue
    public abstract class NewsResponse implements Parcelable {

    public static TypeAdapter<NewsResponse> typeAdapter(Gson gson){
        return new AutoValue_NewsResponse.GsonTypeAdapter(gson);
    }

    @SerializedName("api_text")
    public abstract String isSuccess();

    @SerializedName("news")
    public abstract List<NewsDetails> getNews();
}

my `NewsDetails` class is 

    @AutoValue
    public abstract class NewsDetails implements Parcelable{

    public static TypeAdapter<NewsDetails> typeAdapter(Gson gson){
        return new AutoValue_NewsDetails.GsonTypeAdapter(gson);
    }

    @SerializedName("id")
    public abstract String getNewsId();

    @SerializedName("description")
    public abstract String getDescription();

    @SerializedName("title")
    public abstract String getTitle();

    @SerializedName("category")
    public abstract String getCategory();

    @SerializedName("thumbnail")
    public abstract String getImageUrl();

    @SerializedName("posted_time")
    public abstract String getPostedTime();

    }
My Rxjava call is

            model.getNews("1", "1", OrderBy.DESC)
                .observeOn(AndroidSchedulers.mainThread())
                .doOnError(throwable -> ToastUtils.showShort(throwable.getMessage()))
                .doOnSuccess(newsResponse -> view.setUpRecyclerView(newsResponse.getNews()))
                .subscribeOn(Schedulers.io())
                .subscribe();

My problem is I got this error when I make a Retrofit call

> Failed to invoke public com.ramiissa.dubaiing.data.network.model.news.NewsResponse() with no args

The Api Response from server looks like this

    {
    "api_status": "200",
    "api_text": "success",
    "api_version": "1.5.2",
    "news": [
        {
            "id": "1",
            "title": "news1news1 news1 news1 news1 news1 news1 news1 news1",
            "description": "news1 news1 news1 news1 news1 news1 news1 news1 news1 news1  news1 news1 news1 news1 news1 news1 news1 news1 news1 news1",
            "category": "2",
            "category_name": "English",
            "thumbnail": "http://www.dubai-ing.net/upload/photos/2018/08/nAlMzZ4xZ3XfdMsyT5bj_05_c908f62a43c4f7c8d04e38b29858d9e1_image.jpg",
            "posted_time": "5 hours ago",
            "tags_array": [
                "news1"
            ]
        }
      ]
    }

**Comment by rharter** [comment]
Have you tegisterd the type adapters with the gsonisntance that you provide
to retrofit?

**Comment by alihabbash** [comment]
Actually  I'm a bit newer to AutoValue and gson
So, I'can't figure out but this is my Code for Retrofit:
`    public Retrofit retrofit(OkHttpClient okHttpClient) {
        return new Retrofit.Builder()
                .client(okHttpClient)
                .baseUrl(AppConstants.APP_BASE_URL)
                .addCallAdapterFactory(RxJava2CallAdapterFactory.create())
                .addConverterFactory(GsonConverterFactory.create())
                .build();
    }   `

Please help me to correct my code.
Thank you so much.

**Comment by alihabbash** [comment]
Thanks you so much It's worked but it throws a `stackoverflow` exception
This is the logcat details:

`08-06 14:22:53.213 15795-15795/com.ramiissa.dubaiing E/AndroidRuntime: FATAL EXCEPTION: main
                                                                       Process: com.ramiissa.dubaiing, PID: 15795
                                                                       java.lang.StackOverflowError: stack size 8MB
                                                                           at com.ramiissa.dubaiing.data.network.model.news.NewsResponse.typeAdapter(NewsResponse.java:19)
                                                                           at com.ramiissa.dubaiing.data.network.model.news.NewsResponse.typeAdapter(NewsResponse.java:19)
                                                                           at com.ramiissa.dubaiing.data.network.model.news.NewsResponse.typeAdapter(NewsResponse.java:19)
                                                                           at com.ramiissa.dubaiing.data.network.model.news.NewsResponse.typeAdapter(NewsResponse.java:19)
                                                                           at com.ramiissa.dubaiing.data.network.model.news.NewsResponse.typeAdapter(NewsResponse.java:19)
                                                                           at com.ramiissa.dubaiing.data.network.model.news.NewsResponse.typeAdapter(NewsResponse.java:19)
                                                                           at com.ramiissa.dubaiing.data.network.model.news.NewsResponse.typeAdapter(NewsResponse.java:19)
                                                                           at com.ramiissa.dubaiing.data.network.model.news.NewsResponse.typeAdapter(NewsResponse.java:19)
                                                                           at com.ramiissa.dubaiing.data.network.model.news.NewsResponse.typeAdapter(NewsResponse.java:19)
                                                                           at com.ramiissa.dubaiing.data.network.model.news.NewsResponse.typeAdapter(NewsResponse.java:19)
                                                                           at com.ramiissa.dubaiing.data.network.model.news.NewsResponse.typeAdapter(NewsResponse.java:19)
                                                                           at com.ramiissa.dubaiing.data.network.model.news.NewsResponse.typeAdapter(NewsResponse.java:19)
                                                                           at com.ramiissa.dubaiing.data.network.model.news.NewsResponse.typeAdapter(NewsResponse.java:19)
                                                                           at com.ramiissa.dubaiing.data.network.model.news.NewsResponse.typeAdapter(NewsResponse.java:19)
                                                                           at com.ramiissa.dubaiing.data.network.model.news.NewsResponse.typeAdapter(NewsResponse.java:19)
                                                                           at com.ramiissa.dubaiing.data.network.model.news.NewsResponse.typeAdapter(NewsResponse.java:19)
                                                                           at com.ramiissa.dubaiing.data.network.model.news.NewsResponse.typeAdapter(NewsResponse.java:19)
                                                                           at com.ramiissa.dubaiing.data.network.model.news.NewsResponse.typeAdapter(NewsResponse.java:19)
                                                                           at com.ramiissa.dubaiing.data.network.model.news.NewsResponse.typeAdapter(NewsResponse.java:19)
                                                                           at com.ramiissa.dubaiing.data.network.model.news.NewsResponse.typeAdapter(NewsResponse.java:19)
                                                                           at com.ramiissa.dubaiing.data.network.model.news.NewsResponse.typeAdapter(NewsResponse.java:19)
                                                                           at com.ramiissa.dubaiing.data.network.model.news.NewsResponse.typeAdapter(NewsResponse.java:19)
                                                                           at com.ramiissa.dubaiing.data.network.model.news.NewsResponse.typeAdapter(NewsResponse.java:19)
                                                                           at com.ramiissa.dubaiing.data.network.model.news.NewsResponse.typeAdapter(NewsResponse.java:19)
                                                                           at com.ramiissa.dubaiing.data.network.model.news.NewsResponse.typeAdapter(NewsResponse.java:19)
                                                                           at com.ramiissa.dubaiing.data.network.model.news.NewsResponse.typeAdapter(NewsResponse.java:19)
                                                                           at com.ramiissa.dubaiing.data.network.model.news.NewsResponse.typeAdapter(NewsResponse.java:19)
                                                                           at com.ramiissa.dubaiing.data.network.model.news.NewsResponse.typeAdapter(NewsResponse.java:19)
                                                                           at com.ramiissa.dubaiing.data.network.model.news.NewsResponse.typeAdapter(NewsResponse.java:19)
                                                                           at com.ramiissa.dubaiing.data.network.model.news.NewsResponse.typeAdapter(NewsResponse.java:19)
                                                                           at com.ramiissa.dubaiing.data.network.model.news.NewsResponse.typeAdapter(NewsResponse.java:19)
                                                                           at com.ramiissa.dubaiing.data.network.model.news.NewsResponse.typeAdapter(NewsResponse.java:19)
                                                                           at com.ramiissa.dubaiing.data.network.model.news.NewsResponse.typeAdapter(NewsResponse.java:19)
                                                                           at com.ramiissa.dubaiing.data.network.model.news.NewsResponse.typeAdapter(NewsResponse.java:19)
                                                                           at com.ramiissa.dubaiing.data.network.model.news.NewsResponse.typeAdapter(NewsResponse.java:19)
                                                                           at com.ramiissa.dubaiing.data.network.model.news.NewsResponse.typeAdapter(NewsResponse.java:19)
                                                                           at com.ramiissa.dubaiing.data.network.model.news.NewsResponse.typeAdapter(NewsResponse.java:19)
                                                                           at com.ramiissa.dubaiing.data.network.model.news.NewsResponse.typeAdapter(NewsResponse.java:19)
                                                                           at com.ramiissa.dubaiing.data.network.model.news.NewsResponse.typeAdapter(NewsResponse.java:19)
                                                                           at com.ramiissa.dubaiing.data.network.model.news.NewsResponse.typeAdapter(NewsResponse.java:19)
                                                                       	at com.ramiissa.dubaiing.data.network.model.news.NewsResponse.typeAd
08-06 14:22:53.283 15795-15795/com.ramiissa.dubaiing D/Error: ERR: exClass=java.lang.StackOverflowError
08-06 14:22:53.283 15795-15795/com.ramiissa.dubaiing D/Error: ERR: exMsg=stack size 8MB
08-06 14:22:53.283 15795-15795/com.ramiissa.dubaiing D/Error: ERR: file=NewsResponse.java
08-06 14:22:53.283 15795-15795/com.ramiissa.dubaiing D/Error: ERR: class=com.ramiissa.dubaiing.data.network.model.news.NewsResponse
08-06 14:22:53.283 15795-15795/com.ramiissa.dubaiing D/Error: ERR: method=typeAdapter line=19
08-06 14:22:53.303 15795-15795/com.ramiissa.dubaiing D/Error: ERR: stack=java.lang.StackOverflowError: stack size 8MB
                                                                  at com.ramiissa.dubaiing.data.network.model.news.NewsResponse.typeAdapter(NewsResponse.java:19)
                                                                  at com.ramiissa.dubaiing.data.network.model.news.NewsResponse.typeAdapter(NewsResponse.java:19)
                                                                  at com.ramiissa.dubaiing.data.network.model.news.NewsResponse.typeAdapter(NewsResponse.java:19)
                                                                  at com.ramiissa.dubaiing.data.network.model.news.NewsResponse.typeAdapter(NewsResponse.java:19)
                                                                  at com.ramiissa.dubaiing.data.network.model.news.NewsResponse.typeAdapter(NewsResponse.java:19)
                                                                  at com.ramiissa.dubaiing.data.network.model.news.NewsResponse.typeAdapter(NewsResponse.java:19)
                                                                  at com.ramiissa.dubaiing.data.network.model.news.NewsResponse.typeAdapter(NewsResponse.java:19)
                                                                  at com.ramiissa.dubaiing.data.network.model.news.NewsResponse.typeAdapter(NewsResponse.java:19)
                                                                  at com.ramiissa.dubaiing.data.network.model.news.NewsResponse.typeAdapter(NewsResponse.java:19)
                                                                  at com.ramiissa.dubaiing.data.network.model.news.NewsResponse.typeAdapter(NewsResponse.java:19)
                                                                  at com.ramiissa.dubaiing.data.network.model.news.NewsResponse.typeAdapter(NewsResponse.java:19)
                                                                  at com.ramiissa.dubaiing.data.network.model.news.NewsResponse.typeAdapter(NewsResponse.java:19)
                                                                  at com.ramiissa.dubaiing.data.network.model.news.NewsResponse.typeAdapter(NewsResponse.java:19)
                                                                  at com.ramiissa.dubaiing.data.network.model.news.NewsResponse.typeAdapter(NewsResponse.java:19)
                                                                  at com.ramiissa.dubaiing.data.network.model.news.NewsResponse.typeAdapter(NewsResponse.java:19)
                                                                  at com.ramiissa.dubaiing.data.network.model.news.NewsResponse.typeAdapter(NewsResponse.java:19)
                                                                  at com.ramiissa.dubaiing.data.network.model.news.NewsResponse.typeAdapter(NewsResponse.java:19)
                                                                  at com.ramiissa.dubaiing.data.network.model.news.NewsResponse.typeAdapter(NewsResponse.java:19)
                                                                  at com.ramiissa.dubaiing.data.network.model.news.NewsResponse.typeAdapter(NewsResponse.java:19)
                                                                  at com.ramiissa.dubaiing.data.network.model.news.NewsResponse.typeAdapter(NewsResponse.java:19)
                                                                  at com.ramiissa.dubaiing.data.network.model.news.NewsResponse.typeAdapter(NewsResponse.java:19)
                                                                  at com.ramiissa.dubaiing.data.network.model.news.NewsResponse.typeAdapter(NewsResponse.java:19)
                                                                  at com.ramiissa.dubaiing.data.network.model.news.NewsResponse.typeAdapter(NewsResponse.java:19)
                                                                  at com.ramiissa.dubaiing.data.network.model.news.NewsResponse.typeAdapter(NewsResponse.java:19)
                                                                  at com.ramiissa.dubaiing.data.network.model.news.NewsResponse.typeAdapter(NewsResponse.java:19)
                                                                  at com.ramiissa.dubaiing.data.network.model.news.NewsResponse.typeAdapter(NewsResponse.java:19)
                                                                  at com.ramiissa.dubaiing.data.network.model.news.NewsResponse.typeAdapter(NewsResponse.java:19)
                                                                  at com.ramiissa.dubaiing.data.network.model.news.NewsResponse.typeAdapter(NewsResponse.java:19)
                                                                  at com.ramiissa.dubaiing.data.network.model.news.NewsResponse.typeAdapter(NewsResponse.java:19)
                                                                  at com.ramiissa.dubaiing.data.network.model.news.NewsResponse.typeAdapter(NewsResponse.java:19)
                                                                  at com.ramiissa.dubaiing.data.network.model.news.NewsResponse.typeAdapter(NewsResponse.java:19)
                                                                  at com.ramiissa.dubaiing.data.network.model.news.NewsResponse.typeAdapter(NewsResponse.java:19)
                                                                  at com.ramiissa.dubaiing.data.network.model.news.NewsResponse.typeAdapter(NewsResponse.java:19)
                                                                  at com.ramiissa.dubaiing.data.network.model.news.NewsResponse.typeAdapter(NewsResponse.java:19)
                                                                  at com.ramiissa.dubaiing.data.network.model.news.NewsResponse.typeAdapter(NewsResponse.java:19)
                                                                  at com.ramiissa.dubaiing.data.network.model.news.NewsResponse.typeAdapter(NewsResponse.java:19)
                                                                  at com.ramiissa.dubaiing.data.network.model.news.NewsResponse.typeAdapter(NewsResponse.java:19)
                                                                  at com.ramiissa.dubaiing.data.network.model.news.NewsResponse.typeAdapter(NewsResponse.java:19)
                                                                  at com.ramiissa.dubaiing.data.network.model.news.NewsResponse.typeAdapter(NewsResponse.java:19)
                                                                  at com.ramiissa.dubaiing.data.network.model.news.NewsResponse.typeAdapter(NewsResponse.java:19)
                                                                  at com.ramiissa.dubaiing.data.network.model.news.NewsResponse.typeAdapter(NewsResponse.java:19)
                                                              	at com.ramiissa.dubaiing.data.netw
08-06 14:22:53.303 15795-15795/com.ramiissa.dubaiing D/Error: ERR: TOTAL BYTES WRITTEN: 1678284
08-06 14:22:53.303 15795-15795/com.ramiissa.dubaiing E/JavaBinder: !!! FAILED BINDER TRANSACTION !!!  (parcel size = 1678368)
08-06 14:22:53.313 15795-15795/com.ramiissa.dubaiing E/AndroidRuntime: Error reporting crash
                                                                       android.os.TransactionTooLargeException: data parcel size 1678368 bytes
                                                                           at android.os.BinderProxy.transactNative(Native Method)
                                                                           at android.os.BinderProxy.transact(Binder.java:503)
                                                                           at android.app.ActivityManagerProxy.handleApplicationCrash(ActivityManagerNative.java:5523)
                                                                           at com.android.internal.os.RuntimeInit$UncaughtHandler.uncaughtException(RuntimeInit.java:96)
                                                                           at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:693)
                                                                           at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:690)`

**Comment by alihabbash** [comment]
Thanks It's worked.
I forgot to register the type adapter to Retrofit.
