### ISSUE TITLE
does it working on the customize nested object? 

### ISSUE THREAD

**Issue by bearprada** [rharter/auto-value-gson#31]
for example : 

```
import android.os.Parcelable;
import com.google.auto.value.AutoValue;
import com.google.gson.annotations.SerializedName;

@AutoValue
public abstract class FbAlbum implements Parcelable {
    @SerializedName("id") public abstract String id();
    @SerializedName("name") public abstract String name();
    @SerializedName("count") public abstract int count();
    @SerializedName("picture") public abstract Picture picture();

    public static FbAlbum create(String id, String name, int count, Picture picture) {
        return new AutoValue_FbAlbum(id, name, count, picture);
    }

    public FbAlbum() {}

    @AutoValue
    public abstract static class Picture implements Parcelable {
        @SerializedName("data") abstract PictureData data();

        public static Picture create(String url) {
            return new AutoValue_FbAlbum_Picture(PictureData.create(url));
        }
    }

    @AutoValue
    public abstract static class PictureData implements Parcelable {
        @SerializedName("url") abstract String url();

        public static PictureData create(String url) {
            return new AutoValue_FbAlbum_PictureData(url);
        }
    }
}
```

I will get the error message at runtime

```
Process: com.cardinalblue.android.piccollage.multitouch.photoproto, PID: 28821
java.lang.RuntimeException: Failed to invoke public com.cardinalblue.android.piccollage.model.gson.FbAlbum$Picture() with no args
   at com.google.gson.internal.ConstructorConstructor$3.construct(ConstructorConstructor.java:111)
   at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:206)
   at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:116)
   at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:216)
   at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:40)
   at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:82)
   at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:61)
   at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:116)
   at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:216)
   at com.google.gson.Gson.fromJson(Gson.java:879)
   at com.google.gson.Gson.fromJson(Gson.java:844)
   at com.google.gson.Gson.fromJson(Gson.java:793)
   at com.cardinalblue.android.utils.Utils.parseWithGson(Utils.java:500)
   at com.cardinalblue.android.utils.Utils.parseWithGson(Utils.java:468)
   at com.cardinalblue.android.piccollage.model.gson.FbJsonParser.parse(FbJsonParser.java:33)
   at com.cardinalblue.android.piccollage.model.gson.FbJsonParser.parseAlbums(FbJsonParser.java:22)
   at com.cardinalblue.android.piccollage.view.adapters.FbAlbumListAdapter.parseAlbumList(FbAlbumListAdapter.java:228)
   at com.cardinalblue.android.piccollage.view.adapters.FbAlbumListAdapter.access$300(FbAlbumListAdapter.java:36)
   at com.cardinalblue.android.piccollage.view.adapters.FbAlbumListAdapter$2.onCompleted(FbAlbumListAdapter.java:198)
   at com.facebook.GraphRequest$5.run(GraphRequest.java:1379)
   at android.os.Handler.handleCallback(Handler.java:739)
   at android.os.Handler.dispatchMessage(Handler.java:95)
   at android.os.Looper.loop(Looper.java:148)
   at android.app.ActivityThread.main(ActivityThread.java:5417)
   at java.lang.reflect.Method.invoke(Native Method)
   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
Caused by: java.lang.InstantiationException: Can't instantiate abstract class com.cardinalblue.android.piccollage.model.gson.FbAlbum$Picture
   at java.lang.reflect.Constructor.newInstance(Native Method)
   at com.google.gson.internal.ConstructorConstructor$3.construct(ConstructorConstructor.java:108)
   at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:206) 
   at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:116) 
   at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:216) 
   at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:40) 
   at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:82) 
   at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:61) 
   at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:116) 
   at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:216) 
   at com.google.gson.Gson.fromJson(Gson.java:879) 
   at com.google.gson.Gson.fromJson(Gson.java:844) 
   at com.google.gson.Gson.fromJson(Gson.java:793) 
   at com.cardinalblue.android.utils.Utils.parseWithGson(Utils.java:500) 
   at com.cardinalblue.android.utils.Utils.parseWithGson(Utils.java:468) 
   at com.cardinalblue.android.piccollage.model.gson.FbJsonParser.parse(FbJsonParser.java:33) 
   at com.cardinalblue.android.piccollage.model.gson.FbJsonParser.parseAlbums(FbJsonParser.java:22) 
   at com.cardinalblue.android.piccollage.view.adapters.FbAlbumListAdapter.parseAlbumList(FbAlbumListAdapter.java:228) 
   at com.cardinalblue.android.piccollage.view.adapters.FbAlbumListAdapter.access$300(FbAlbumListAdapter.java:36) 
   at com.cardinalblue.android.piccollage.view.adapters.FbAlbumListAdapter$2.onCompleted(FbAlbumListAdapter.java:198) 
   at com.facebook.GraphRequest$5.run(GraphRequest.java:1379) 
   at android.os.Handler.handleCallback(Handler.java:739) 
   at android.os.Handler.dispatchMessage(Handler.java:95) 
   at android.os.Looper.loop(Looper.java:148) 
   at android.app.ActivityThread.main(ActivityThread.java:5417) 
```

**Comment by rharter** [comment]
This isn't generating a type adapter. Check the readme, you need a public static method returning TyeAdapter for this to generate the type adapter, then you'll have to register that with Gson for it to be used.

**Comment by bearprada** [comment]
thanks @rharter , i will check the readme again

**Comment by rharter** [comment]
I'm closing this issue as I haven't heard any resolution.  If this is unresolved and you've identified an issue, feel free to reopen it.
