### ISSUE TITLE
Android Studio multiple modules- NoClassDefFoundError Parcelable

### ISSUE THREAD

**Issue by muddin1** [rharter/auto-value-gson#80]
I couldn't figure out what's causing this. I have a 3 module project two of which have the third  as a dependency. When I build `module_one` everything works fine, but when I try building `module_two` I get this weird error. Running with stacktrace makes me guess that `android/os/Parcelable` should've been `android.os.Parcelable`.

Anyone else faced this before?

```
:module_two:compileMockDebugJavaWithJavac FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':consumer:compileMockDebugJavaWithJavac'.
> java.lang.NoClassDefFoundError: android/os/Parcelable

* Try:
Run with --info or --debug option to get more log output.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':consumer:compileMockDebugJavaWithJavac'.
    at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:69)
    at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:46)
    at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExecuter.execute(PostExecutionAnalysisTaskExecuter.java:35)
    at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:66)
    at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
    at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:52)
    at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
    at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:53)
    at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
    at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:203)
    at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:185)
    at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:66)
    at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:50)
    at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
    at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
Caused by: java.lang.RuntimeException: java.lang.NoClassDefFoundError: android/os/Parcelable
    at com.sun.tools.javac.main.Main.compile(Main.java:553)
    at com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:129)
    at com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:138)
    at org.gradle.api.internal.tasks.compile.JdkJavaCompiler.execute(JdkJavaCompiler.java:46)
    at org.gradle.api.internal.tasks.compile.JdkJavaCompiler.execute(JdkJavaCompiler.java:33)
    at org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler.delegateAndHandleErrors(NormalizingJavaCompiler.java:104)
    at org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler.execute(NormalizingJavaCompiler.java:53)
    at org.gradle.api.internal.tasks.compile.NormalizingJavaCompiler.execute(NormalizingJavaCompiler.java:38)
    at org.gradle.api.internal.tasks.compile.CleaningJavaCompilerSupport.execute(CleaningJavaCompilerSupport.java:35)
    at org.gradle.api.internal.tasks.compile.CleaningJavaCompilerSupport.execute(CleaningJavaCompilerSupport.java:25)
    at org.gradle.api.tasks.compile.JavaCompile.performCompilation(JavaCompile.java:163)
    at org.gradle.api.tasks.compile.JavaCompile.compile(JavaCompile.java:145)
    at org.gradle.api.tasks.compile.JavaCompile.compile(JavaCompile.java:93)
    at com.android.build.gradle.tasks.factory.AndroidJavaCompile.compile(AndroidJavaCompile.java:49)
    at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:75)
    at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$IncrementalTaskAction.doExecute(AnnotationProcessingTaskFactory.java:245)
    at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:221)
    at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$IncrementalTaskAction.execute(AnnotationProcessingTaskFactory.java:232)
    at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:210)
    at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
    at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
    ... 14 more
Caused by: java.lang.NoClassDefFoundError: android/os/Parcelable
    at com.ryanharter.auto.value.gson.AutoValueGsonExtension.getDefaultValue(AutoValueGsonExtension.java:465)
    at com.ryanharter.auto.value.gson.AutoValueGsonExtension.createReadMethod(AutoValueGsonExtension.java:380)
    at com.ryanharter.auto.value.gson.AutoValueGsonExtension.createTypeAdapter(AutoValueGsonExtension.java:312)
    at com.ryanharter.auto.value.gson.AutoValueGsonExtension.generateClass(AutoValueGsonExtension.java:185)
    at com.google.auto.value.processor.AutoValueProcessor.writeExtensions(AutoValueProcessor.java:474)
    at com.google.auto.value.processor.AutoValueProcessor.processType(AutoValueProcessor.java:460)
    at com.google.auto.value.processor.AutoValueProcessor.process(AutoValueProcessor.java:150)
    at com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:794)
    at com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:705)
    at com.sun.tools.javac.processing.JavacProcessingEnvironment.access$1800(JavacProcessingEnvironment.java:91)
    at com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1035)
    at com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1176)
    at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1170)
    at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:856)
    at com.sun.tools.javac.main.Main.compile(Main.java:523)
    ... 34 more
Caused by: java.lang.ClassNotFoundException: android.os.Parcelable
    ... 49 more


BUILD FAILED

Total time: 4.085 secs
```

**Comment by muddin1** [comment]
This started happening when I upgraded to the newer versions

From:
```
    autoValueVersion = '1.3-rc2'
    avAnnotationsVersion = '1.2-update1'
    avParcelVersion = '0.2.3-rc2'
    avGsonVersion = '0.4.2'
    avWithVersion = '1.0.0-rc1'
```
To:
```
    autoValueVersion = '1.3'
    avAnnotationsVersion = '1.3'
    avParcelVersion = '0.2.5'
    avGsonVersion = '0.4.3'
    avWithVersion = '1.0.0-rc1'
```

**Comment by rharter** [comment]
Can you look in the `build` directory to see what's actually being generated?  You should be able to find it in `build/generated/source/apt`.

**Comment by muddin1** [comment]
I see that out of all the @AutoValue classes, only a handful have their implementations generated.

Not sure if this is comprehensible. Let me know if more details are needed.

**Comment by rharter** [comment]
If the processor fails at some point, that might be expected.  We need to find the source of the `android/os/Parcelable`.  Since the error is `Caused by: java.lang.ClassNotFoundException: android.os.Parcelable`, I'm expecting that the source is formatted correctly.  Can you please check the generated source files to verify?

**Comment by muddin1** [comment]
There are only 3 AutoValue classes whose sources have been generated.
And here's the interesting part: One could only generate a $$AutoValue_Name (auto-value) and didn't proceed further. $AutoValue_Name should have been generated by the gson extension and AutoValue_Name by the parcel extension.

AutoValue class:
```
package com.example;

import android.os.Parcelable;
import android.support.annotation.NonNull;
import android.support.annotation.Nullable;

import com.google.auto.value.AutoValue;
import com.google.gson.Gson;
import com.google.gson.TypeAdapter;
import com.example.data.User;

@AutoValue
public abstract class Request implements Parcelable {

    public static Request create(@NonNull User user, @Nullable String description) {
        return new AutoValue_Request(user, description);
    }

    public static TypeAdapter<Request> typeAdapter(Gson gson) {
        return new AutoValue_Request.GsonTypeAdapter(gson);
    }

    @NonNull
    public abstract User user();

    @Nullable
    public abstract String description();
}
```

auto-value generated: `$$AutoValue_Request`
```
package com.example;

import android.support.annotation.NonNull;
import android.support.annotation.Nullable;
import com.example.data.User;

 abstract class $$AutoValue_Request extends Request {

  private final User user;
  private final String description;

  $$AutoValue_Request(
      User user,
      @Nullable String description) {
    if (user == null) {
      throw new NullPointerException("Null user");
    }
    this.user = user;
    this.description = description;
  }

  @NonNull
  @Override
  public User user() {
    return user;
  }

  @Nullable
  @Override
  public String description() {
    return description;
  }

  @Override
  public String toString() {
    return "Request{"
        + "user=" + user + ", "
        + "description=" + description
        + "}";
  }

  @Override
  public boolean equals(Object o) {
    if (o == this) {
      return true;
    }
    if (o instanceof Request) {
      Request that = (Request) o;
      return (this.user.equals(that.user()))
           && ((this.description == null) ? (that.description() == null) : this.description.equals(that.description()));
    }
    return false;
  }

  @Override
  public int hashCode() {
    int h = 1;
    h *= 1000003;
    h ^= this.user.hashCode();
    h *= 1000003;
    h ^= (description == null) ? 0 : this.description.hashCode();
    return h;
  }

}
```

auto-value-gson: `$AutoValue_Request`
```
None
```

auto-value-parcel: `AutoValue_Request`
```
None
```

**Comment by rharter** [comment]
This is an Android module, right?  As opposed to a java only module?

**Comment by muddin1** [comment]
That's correct.

**Comment by muddin1** [comment]
@rharter Did this information help you get anywhere?

**Comment by rharter** [comment]
I haven't been able to repro this one.  Can you make a simple project demonstrating this issue, please?

**Comment by hister** [comment]
https://github.com/hister/AutoValueGsonIssue80

this is a simple project demonstrating this issue.

as I understood it this problem happens when a property witch is Parcelable in one of the dependencies

**Comment by hister** [comment]
a temporary fix would be to add a dependency to android.jar

apt files('sdkdir/platforms/android-25/android.jar')

**Comment by muddin1** [comment]
@hister Thanks a lot for posting the example project.

@rharter This project produces the exact error I am having. Hope it is useful in debugging.

**Comment by hister** [comment]
@rharter could you take a look at this ?

**Comment by Piasy** [comment]
I have the same issue, and @hister 's workaround works.

**Comment by hzsweers** [comment]
Per talking with the android tools team, a future version of the android gradle plugin's `annotationProcessor` configuration will have the android jar on the classpath, so this will just have to wait until then.

Ref: https://code.google.com/p/android/issues/detail?id=231914

**Comment by gengjiawen** [comment]
If you prefer simple export, you can use this
```gradle
apt files("$android.sdkDirectory.path/platforms/android-26/android.jar")
```
